name: Sync Sheet to Firebase

on:
  schedule:
    # Runs at the top of every hour
    - cron: '0 * * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # We just need pandas, gspread, firebase, and auth
          pip install pandas gspread gspread-dataframe firebase-admin oauth2client

      - name: Authenticate and Run Script
        run: |
          echo "${{ secrets.GSPREAD_CREDENTIALS }}" > credentials.json
          python run_nfl_update.py
